### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by untitaker** [pallets/meta#1]
A potentially delicate topic. Keep in mind that there are other options besides copy-pasting the contributor covenant.

@pallets/global-committers

**Comment by ThiefMaster** [comment]
I wouldn't add one at all - most people are decent and have common sense. 
And those who are just dicks won't care about a CoC anyway.

**Comment by untitaker** [comment]
I think it at least requires clarification whether we should tolerate borderline things such as:

* sexualizing nicknames
* "edgy" jokes about minorities

>most people are decent and have common sense.

I would say that it heavily depends on the environment (and the degree of anonymity) how people behave and which language they use.

>And those who are just dicks won't care about a CoC anyway.

I rather suspect a majority would cease all involvement rather than just ignoring the rules.

---

Generally I'd like to define a standard process for dealing with trolls. And such a process would require having concrete rules (no matter how obvious).

**Comment by DasIch** [comment]
> I wouldn't add one at all - most people are decent and have common sense. And those who are just dicks won't care about a CoC anyway.

What is decent? What does it mean for someone to have common sense? There isn't one generally accepted definition, every community has it's own and what some communities consider decent and to be common sense is really fucking awful. Especially communities that talk about decency and accuse others of indeceny seem to be the worst of all.

A CoC allows us to be transparent and explicit about where we stand. It allows us to quickly and loudly say "You're welcome here", to the people that in this fucked up world are too often discriminated against and can't at all be sure of being welcome. 

Are dicks going to care about whether there is a CoC or not? No. In fact they might be dicks to us just because of a CoC. That shouldn't be a reason for us not to have a CoC. Also let's not pretend that CoCs are somehow a novel concept that suddenly appeared in tech just now and doesn't exist anywhere else. Almost all organizations beyond some size and maturity have some form of CoC, possibly under a different name, and that has been true for millenia. No doubt not long after humanity became capable of reading and writing that someone wrote one down. To believe that social groups that come together to develop open source software are somehow so incredibly special that they don't need one is ridiculously arrogant.

As @untitaker mentioned a CoC along with a well defined process for dealing with violations also makes it easier on those having to deal with assholes. It makes it simple to respond quickly and confidently.

Personally I'm +1 on the Contributor Convenant. Many people have been involved in creating it, every detail has been critized and analyzed. The authors have shown themselves to be very receptive to criticism and the CC has been adapted and fixed in response to criticism. At this point every single word in the CC is carefully considered. It would be incredibly difficult to come up with something better.

The Contributor Covenant also has the advantage of familiarity. This means that someone new to the project instantly knows the rules and doesn't have to read the CoC first. This is valueable in the same way common style guides like PEP 8 are valueable. For this reason it wouldn't be sufficient to be better than the CC, you need to be a lot better. I doubt that can be achieved.

That being said the Contributor Convenant isn't sufficient on it's own. You need a process to deal with violations otherwise it's just show.

**Comment by untitaker** [comment]
I just figured we actually have sort of a CoC: https://www.palletsproject.com/governance/rules-of-engagement/

Ironically it says that "we need to set up rules", but then doesn't define them ;)

**Comment by mitsuhiko** [comment]
My personal opinion on code of conducts of any sort is that once there is one, people become lawyers around them.  I do not want that.  That's also why what we have currently is called "rules of engagement" and intentionally vague.  I do not want people to take anything that is written somewhere to have arguments about what is unacceptable/acceptable and what is not.

To make this clear: I don't want any shitty behaviour from anyone and I do not see a reason to have to lay out what exactly shitty behaviour is and what is not.

**Comment by untitaker** [comment]
>My personal opinion on code of conducts of any sort is that once there is one, people become lawyers around them. I do not want that

In principle this can happen with any kind of ruleset for any kind of mechanism, this doesn't mean that rules in general are a bad thing.

> I do not want people to take anything that is written somewhere to have arguments about what is unacceptable/acceptable and what is not.

The CoC is about *ending* such arguments. Moral discussions about what is acceptable/unacceptable are unavoidable with or without CoC, but I definetly think that having a (clear) definition of unacceptable behavior helps avoiding such discussions.

Here's a completely unrelated example for comparison (sic): Historically, what RFCs and specifications have spawned more arguments: The ambiguous or unambigous ones?

**Comment by mitsuhiko** [comment]
> The CoC is about ending such arguments. Moral discussions about what is acceptable/unacceptable are unavoidable with or without CoC, but I definetly think that having a (clear) definition of unacceptable behavior helps avoiding such discussions.

The only difference in the argument will be that the CoC would have to be amended when an argument breaks out and it has not been sufficiently covered. Honestly though, what would you want to add to the rules of engagement which is currently missing?

**Comment by mitsuhiko** [comment]
Also if there are concrete cases of where a CoC would have helped in the past I'm happy to change my opinion on that issue.  However from what I remember we generally locked threads before damage was done.  (Ignoring one particular incident which I remember very well which however would not have been avoided by the presence or absence of a code of conduct)

**Comment by untitaker** [comment]
>Honestly though, what would you want to add to the rules of engagement which is currently missing?

Oh, this is where the real controversity starts :)

See https://github.com/pallets/meta/issues/1#issuecomment-204570354:

>* sexualizing nicknames
>* "edgy" jokes about minorities

--

>which however would not have been avoided by the presence or absence of a code of conduct

It's hard to argue against this one as I'm not sure if we're thinking of the same incident. If you mean the same one, I think it's arguable and depends on the CoC we choose.

**Comment by mitsuhiko** [comment]
@untitaker but now you added an enumeration which clearly is not complete :) Those are by far not the only things I do not want to see on bug trackers.

**Comment by untitaker** [comment]
@mitsuhiko There is stuff so obvious that it probably doesn't need to be mentioned (pornography?), I think it's sufficient to clarify the top-n things people disagree about. The end result would probably look similar to the [Contributor Covenant's list](http://contributor-covenant.org/version/1/4/)

**Comment by RonnyPfannschmidt** [comment]
a rule that goes for education with a fallback of punishment for undesired behaviors seems more efficient than going for incomplete listings and political tools

desired/undesired behaviors can be deduced from the goals of the community/project and the effect of the behavior in question on the community and individuals

**Comment by mitsuhiko** [comment]
@untitaker i will send a PR with some of the stuff stolen from there.

**Comment by davidism** [comment]
The San Diego Python group uses this: http://www.pythonsd.org/pages/code-of-conduct.html

**Comment by LindsayYoung** [comment]
Spoke with @davidism and the decision was to use [Contributor Covenant](https://www.contributor-covenant.org). It has easy GitHub integration and quality text.

For context, Here is a comparison of different codes of conduct [from geek feminism](https://geekfeminism.wikia.org/wiki/Code_of_conduct_evaluations): 
Contributor Covenant looks like it is a good default because it covers: 
 - Descriptions of common but unacceptable behavior
 - Reporting instructions with contact information
 - Information about enforcement
 - Clear demarcation between anti-harassment policy and general community guidelines

**Comment by untitaker** [comment]
I'm very happy this is happening!

**Comment by FelixWolf** [comment]
Personally, as someone who uses Flask/Sqlalchemy, It saddens me to see the choice being Contributor Covenant.
It is politically charged and is used as a "social weapon" by it's creator. It shouldn't be treated as a neutral CoC. The fact I am scared to even write this comment should be proof enough.
PSF's and Debian's are examples of neutral CoCs.
